Update initialize.yml

diff --git a/.github/workflows/initialize.yml b/.github/workflows/initialize.yml
--- a/.github/workflows/initialize.yml
+++ b/.github/workflows/initialize.yml
@@ -8,9 +8,79 @@ on:
     - 'init'
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+
   
 jobs:
+  first-Initialisation:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Generate GitHub App Token
+        id: generate-token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ secrets.APP_ID }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY }}
+          owner: ${{ github.repository_owner }}  # scopes token to whole org
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          token: "${{ steps.generate-token.outputs.token }}"
+      
+      - name: dispatch to Default designe 
+        env:
+          GH_TOKEN: "${{ steps.generate-token.outputs.token }}"
+        run: |
+          response=$(curl -s -w "\n%{http_code}" \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            https://api.github.com/repos/ch-sz-geo/Test_DefaultDesigne/dispatches \
+            -d '{"event_type":"add-dispatch-step","client_payload":{"ref":"main", "repo_name": "${{ github.event.repository.name }}" }}')
+
+          #This section is to fail the task when the dispach to the target repo didn't work
+          http_code=$(echo "$response" | tail -n1)
+          body=$(echo "$response" | head -n -1)
+          
+          echo "HTTP Status: $http_code"
+          echo "Response: $body"
+          
+          if [ "$http_code" -ne 204 ]; then
+            echo "::error::Dispatch failed with status $http_code: $body"
+            exit 1
+          fi
+      
+      - name: updtate the initialize.yml
+        env:
+          GH_TOKEN: "${{ steps.generate-token.outputs.token }}"
+        run: |
+          ls
+          cd .github/workflows
+          touch temp.yml
+          sed -n '1,13p' initialize.yml > temp.yml
+          sed -n '80,81p' initialize.yml >> temp.yml
+          sed -n '84,140p' initialize.yml >> temp.yml
+
+          mv temp.yml initialize.yml
+
+          cd ../..
+
+          git status
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+          
+          git add .github/workflows/initialize.yml
+          git status
+          git diff --cached --quiet && echo "No changes to commit" && exit 0
+          git commit -m "updated the initialize.yml"
+          git push
+          
+          
+
   init-files:
+  
+    needs: first-Initialisation
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     
@@ -68,4 +138,3 @@ jobs:
           git add README.adoc index.html 
           git commit -am "Initialize files from init.txt"
           git push
-          
